Adding first paginated method, not working
```
error[E0599]: the method `limit` exists for reference `&Paginated<T>`, but its trait bounds were not satisfied
  --> src/bin/extending_pager.rs:20:48
   |
20 |         out.push_bind_param::<BigInt, _>(&self.limit())?;
   |                                                ^^^^^ method cannot be called on `&Paginated<T>` due to unsatisfied trait bounds
...
50 | pub struct Paginated<T> {
   | -----------------------
   | |
   | doesn't satisfy `Paginated<T>: QueryDsl`
   | doesn't satisfy `Paginated<T>: Table`
   |
   = note: the following trait bounds were not satisfied:
           `&Paginated<T>: Table`
           which is required by `&Paginated<T>: QueryDsl`
           `&&Paginated<T>: Table`
           which is required by `&&Paginated<T>: QueryDsl`
           `&mut &Paginated<T>: Table`
           which is required by `&mut &Paginated<T>: QueryDsl`
           `Paginated<T>: Table`
           which is required by `Paginated<T>: QueryDsl`
           `&mut Paginated<T>: Table`
           which is required by `&mut Paginated<T>: QueryDsl`
```